config/routes.rb
Rails.application.routes.draw do
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :task
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :tasks
end

app/models/responsible.rb
class Responsible < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :team
  belongs_to :customer
  has_many :responsibles
  has_many :blocks
end

app/models/team.rb
class Team < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :tasks
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :teams
  has_many :responsibles
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  has_many :teams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end

  def create
    puts(task_params)
    @task = Task.new(task_params)

    @task.team = Team.find(params[:task][:team_id])
    @task.customer = Customer.find(params[:task][:customer_id])

    if @task.save
      redirect_to tasks_path, notice: 'Task was successfully created.'
    else
      flash.now[:alert] = 'Task was not created.'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(
      :title,
      :description,
      :due_date,
      :status,
      :team_id,
      :customer_id,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp,container-queries"></script>
  </head>

  <body>
    <main class="container mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/button/_index.html.erb
<% type =  type.presence || 'default' %>
<a href="<%= action %>" data-type="<%= type %>" class="bg-blue-600 p-2 rounded shadow text-white
  data-[type=outline]:bg-transparent data-[type=outline]:text-blue-600 data-[type=outline]:border data-[type=outline]:border-blue-600
">
  <%= inner_text %>
</a>

app/views/shared/input_select/_index.html.erb
<div class="flex flex-col">
  <%= form.label field, label_text %>
  <%= form.select field, options_for_select(input_options), class: 'custom-select-class' %>

  <% resource.errors.full_messages_for(field).each do |message| %>
    <div class="text-red-500"><%= message %></div>
  <% end %>
</div>

app/views/shared/input_text/_index.html.erb
<div class="flex flex-col">
  <%= form.label field, label_text %>
  <%= form.text_field field, option_html_attributes(input_options.presence || {}) %>
  <% resource.errors.full_messages_for(field).each do |message| %>
    <div class="text-red-500"><%= message %></div>
  <% end %>
</div>

app/views/tasks/components/form/_index.html.erb
<%= form_with model: task do |form| %>
  <div class="space-y-4">
    <%= render 'shared/input_text/index',
               form: form,
               field: :title,
               resource: @task,
               input_options: nil,
               label_text: "Problema" %>
    <%= render 'shared/input_text/index',
               form: form,
               field: :description,
               resource: @task,
               input_options: nil,
               label_text: 'Critérios de aceite' %>
    <%= render 'shared/input_select/index',
               form: form,
               field: :team_id,
               resource: @task,
               label_text: "Time responsável",
               input_options: Team.all.pluck(:name, :id) %>
    <%= render 'shared/input_select/index',
               form: form,
               field: :customer_id,
               resource: @task,
               label_text: "Clientes",
               input_options: Customer.all.pluck(:name, :id)  %>
    <% @task.errors.full_messages.each do |message| %>
      <div class="text-red-500"><%= message %></div>
    <% end %>
  </div>
  <div class="flex gap-2 items-center mt-4">
    <%= render 'shared/button/index', inner_text: "Cancelar", action: tasks_path, type: "outline" %>
    <div>
      <%= form.submit "Salvar", class: "bg-blue-600 rounded shadow text-white p-2 hover:opacity-80 transition" %>
    </div>
  </div>
<% end %>

app/views/tasks/index.html.erb
<section class="container gap-6 mx-auto my-6">
  <%= render 'shared/button/index', inner_text: 'Adicionar task', action: new_task_path %>
  <div class="flex my-12 gap-4">
    <% if @tasks.any? %>
      <% @tasks.each do | task | %>
        <div class="bg-neutral-100 p-4 rounded min-w-96 border
        hover:scale-105 hover:cursor-pointer transition">
          <h2><%= task.title %></h2>
          <p><%= task.description %></p>
          <span><%= task.status %></span>
        </div>
      <% end %>
    <% else %>
      <div>
        <p>
          Não há nenhuma task criada,
          <a class="text-blue-600" href="<%= new_task_path %>">clique aqui</a>
          para adicionar.
        </p>
      </div>
    <% end %>
  </div>
</section>

app/views/tasks/new.html.erb
<h2> Nova Task</h2>
<%= render 'tasks/components/form/index', task: @task%>